'\" t
.\"     Title: true
.\"    Author: Mo McRoberts
.\" Generator: DocBook XSL Stylesheets v1.77.1 <http://docbook.sf.net/>
.\"      Date: 09/03/2012
.\"    Manual: User Commands
.\"    Source: System Manager's Manual
.\"  Language: English
.\"
.TH "TRUE" "1" "09/03/2012" "System Manager's Manual" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
true \- return true value
.SH "SYNOPSIS"
.HP \w'\fBtrue\fR\ 'u
\fBtrue\fR
.SH "DESCRIPTION"
.PP
The
\fBtrue\fR
utility exits with a successful exit status\&.
.SH "OPTIONS"
.PP
The
\fBtrue\fR
utility does not perform any option processing\&.
.SH "DIAGNOSTICS"
.PP
The
\fBtrue\fR
utility always exits with a status of
\fB0\fR\&.
.SH "STANDARDS"
.PP
The
\fBtrue\fR
utility conforms to the
Single UNIX Specification, Version 3 (SUSv3)\&.
.SH "SEE ALSO"
.PP

\fBfalse\fR(1),
\fByes\fR(1)\&.
